version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: solana-monitor-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: solana-monitor

  backend:
    build: ./backend
    container_name: solana-monitor-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/solana-monitor
      - SOLANA_RPC=https://api.mainnet-beta.solana.com
      - MONITOR_WALLETS=${MONITOR_WALLETS:-}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: solana-monitor-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
